import React from 'react';
import Article from './components/Article';
import Text from './components/Text';

const HomePage = () => {
  return (
    <div className="p-10">
      <Article
        imageSrc="2ASP5507.jpg"
        text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada fames ac turpis egestas integer. Arcu non sodales neque sodales ut etiam sit. Bibendum ut tristique et egestas quis. Facilisis volutpat est velit egestas dui. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Elit duis tristique sollicitudin nibh sit amet. Venenatis urna cursus eget nunc scelerisque viverra. Dignissim cras tincidunt lobortis feugiat vivamus. Amet nulla facilisi morbi tempus. Augue neque gravida in fermentum et sollicitudin ac orci. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Lectus urna duis convallis convallis tellus id interdum. Vulputate eu scelerisque felis imperdiet proin fermentum leo. In dictum non consectetur a erat nam at lectus urna. A erat nam at lectus urna duis convallis convallis. Egestas integer eget aliquet nibh praesent tristique. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Nullam vehicula ipsum a arcu cursus."
      />
      <Text text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada fames ac turpis egestas integer. Arcu non sodales neque sodales ut etiam sit. Bibendum ut tristique et egestas quis. Facilisis volutpat est velit egestas dui. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Elit duis tristique sollicitudin nibh sit amet. Venenatis urna cursus eget nunc scelerisque viverra. Dignissim cras tincidunt lobortis feugiat vivamus. Amet nulla facilisi morbi tempus. Augue neque gravida in fermentum et sollicitudin ac orci. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Lectus urna duis convallis convallis tellus id interdum. Vulputate eu scelerisque felis imperdiet proin fermentum leo. In dictum non consectetur a erat nam at lectus urna. A erat nam at lectus urna duis convallis convallis. Egestas integer eget aliquet nibh praesent tristique. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Nullam vehicula ipsum a arcu cursus.

Tristique nulla aliquet enim tortor at auctor. Odio morbi quis commodo odio aenean sed. Faucibus pulvinar elementum integer enim neque volutpat. Est lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Aliquet risus feugiat in ante metus. Etiam sit amet nisl purus in mollis. Etiam erat velit scelerisque in. Enim praesent elementum facilisis leo. Proin sed libero enim sed faucibus turpis in eu mi. Non curabitur gravida arcu ac. Ac turpis egestas integer eget. Cursus sit amet dictum sit amet justo donec enim diam. Id cursus metus aliquam eleifend mi in nulla posuere. At imperdiet dui accumsan sit amet nulla. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Vivamus at augue eget arcu dictum varius duis at consectetur. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum.

Mauris ultrices eros in cursus turpis massa. Eget gravida cum sociis natoque penatibus et magnis. Risus nullam eget felis eget. Urna nunc id cursus metus aliquam eleifend mi in nulla. Viverra nam libero justo laoreet sit amet cursus sit amet. Pulvinar proin gravida hendrerit lectus. Arcu cursus euismod quis viverra nibh cras pulvinar. Nunc mattis enim ut tellus elementum sagittis. Quis imperdiet massa tincidunt nunc. Mollis aliquam ut porttitor leo a diam. Mauris pellentesque pulvinar pellentesque habitant morbi. Amet venenatis urna cursus eget nunc scelerisque viverra. Gravida cum sociis natoque penatibus et magnis dis parturient. Sed tempus urna et pharetra pharetra. Lacus sed turpis tincidunt id aliquet risus feugiat in. Nunc lobortis mattis aliquam faucibus purus in massa. Aliquet bibendum enim facilisis gravida neque convallis. Arcu dui vivamus arcu felis. Mattis enim ut tellus elementum sagittis vitae et leo. Dui ut ornare lectus sit.

At in tellus integer feugiat. Amet massa vitae tortor condimentum lacinia quis. Fusce ut placerat orci nulla pellentesque dignissim enim. Sed vulputate odio ut enim blandit volutpat. Tincidunt id aliquet risus feugiat in ante metus. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Donec et odio pellentesque diam volutpat commodo. Lacus luctus accumsan tortor posuere ac ut. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Vel turpis nunc eget lorem dolor. Duis at tellus at urna condimentum mattis pellentesque id. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Congue eu consequat ac felis donec et odio pellentesque diam.

In cursus turpis massa tincidunt dui ut ornare lectus sit. Pretium viverra suspendisse potenti nullam ac tortor. Tincidunt dui ut ornare lectus sit. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Ridiculus mus mauris vitae ultricies leo integer malesuada. Auctor urna nunc id cursus metus aliquam. Donec ac odio tempor orci dapibus ultrices. Sit amet facilisis magna etiam tempor. Nullam non nisi est sit amet facilisis magna etiam. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. In vitae turpis massa sed. Diam donec adipiscing tristique risus nec feugiat in fermentum. Natoque penatibus et magnis dis parturient montes nascetur. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Tellus id interdum velit laoreet id donec ultrices. Diam ut venenatis tellus in metus vulputate eu scelerisque felis." />
    </div>
  );
};

export default HomePage;